Repository solve-nyang/solve-nyang-api, pull requests merged in 2025-01, with the labels that each got.

#3 feat: 사용자 아바타 조회 기능 구현 - 김지영
  src/main/java/com/ssafy/solvedpick/avatars/domain/Avatar.java
  src/main/java/com/ssafy/solvedpick/avatars/repository/OwnedAvatarRepository.java
  src/main/java/com/ssafy/solvedpick/gacha/service/GachaService.java
  src/main/java/com/ssafy/solvedpick/members/domain/Member.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/domain/OwnedAvatar.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/dto/MemberAvatarResponseDTO.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/dto/OwnedAvatarDTO.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/presentation/OwnedAvatarController.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/repository/OwnedAvatarRepository.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/OwnedAvatarService.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/impl/OwnedAvatarServiceImpl.java
Labels: feature

#7 feat: 사용자가 캐릭터 상태를 변경하는 기능 추가 - 이동규
  src/main/java/com/ssafy/solvedpick/ownedavatar/domain/OwnedAvatar.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/presentation/OwnedAvatarController.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/repository/OwnedAvatarRepository.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/OwnedAvatarService.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/impl/OwnedAvatarServiceImpl.java
Labels: feature

#10 Feature: 회원 및 보안 기능 구현 - 조성빈
  build.gradle
  src/main/java/com/ssafy/solvedpick/accounts/domain/VerificationKey.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/MembernameDTO.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/SignInFormDTO.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/SignupFormDTO.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/TokenResponse.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/UsernameResponse.java
  src/main/java/com/ssafy/solvedpick/accounts/presentation/AccountController.java
  src/main/java/com/ssafy/solvedpick/accounts/repository/VerificationKeyRepository.java
  src/main/java/com/ssafy/solvedpick/accounts/scheduler/VerificationKeyScheduler.java
  src/main/java/com/ssafy/solvedpick/accounts/service/SigninService.java
  src/main/java/com/ssafy/solvedpick/accounts/service/SignupService.java
  src/main/java/com/ssafy/solvedpick/accounts/service/VerificationService.java
  src/main/java/com/ssafy/solvedpick/config/SecurityConfig.java
  src/main/java/com/ssafy/solvedpick/gacha/service/GachaService.java
  src/main/java/com/ssafy/solvedpick/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ssafy/solvedpick/jwt/JwtAuthenticationToken.java
  src/main/java/com/ssafy/solvedpick/jwt/JwtConfig.java
  src/main/java/com/ssafy/solvedpick/jwt/JwtUtil.java
  src/main/java/com/ssafy/solvedpick/members/domain/Member.java
  src/main/java/com/ssafy/solvedpick/members/presentation/MemberController.java
  src/main/java/com/ssafy/solvedpick/members/repository/MemberRepository.java
  src/main/java/com/ssafy/solvedpick/members/service/MemberService.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/domain/OwnedAvatar.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/impl/OwnedAvatarServiceImpl.java
Labels: feature

#11 feat: 문제 등급별 점수 환산을 위해 enum 추가 - 이동규
  src/main/java/com/ssafy/solvedpick/avatars/domain/Grade.java
  src/main/java/com/ssafy/solvedpick/common/grade/Grade.java
  src/main/java/com/ssafy/solvedpick/common/point/Point.java
  src/main/java/com/ssafy/solvedpick/gacha/service/GachaService.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/impl/OwnedAvatarServiceImpl.java
  src/main/resources/application-local.yml
Labels: feature

#12 chore: webconfig에 프론트엔드 배포 url 추가 - 이동규
  src/main/java/com/ssafy/solvedpick/config/WebConfig.java
  src/main/resources/application-local.yml
Labels: chore

#14 [Fix] Login 문제 해결 - famo1245
  build.gradle
  src/main/java/com/ssafy/solvedpick/accounts/domain/VerificationKey.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/MemberNameDTO.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/TokenResponse.java
  src/main/java/com/ssafy/solvedpick/accounts/dto/VerificationResponseDTO.java
  src/main/java/com/ssafy/solvedpick/accounts/presentation/AccountController.java
  src/main/java/com/ssafy/solvedpick/accounts/service/SigninService.java
  src/main/java/com/ssafy/solvedpick/accounts/service/SignupService.java
  src/main/java/com/ssafy/solvedpick/accounts/service/VerificationService.java
  src/main/java/com/ssafy/solvedpick/common/dto/ResponseMessageDTO.java
  src/main/java/com/ssafy/solvedpick/jwt/JwtAuthenticationFilter.java
  src/main/resources/application-local.yml
Labels: bugfix

#15 refactor: 엔티티 수정 - 이동규
  build.gradle
  src/main/java/com/ssafy/solvedpick/accounts/domain/VerificationKey.java
  src/main/java/com/ssafy/solvedpick/avatars/domain/Avatar.java
  src/main/java/com/ssafy/solvedpick/members/domain/Member.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/domain/OwnedAvatar.java
Labels: refactor

#17 [Fix] CD 스크립트 권한 부여 - 김지영
  .github/workflows/solve-nyang-deploy.yml
Labels: bugfix

#18 [Fix] CD 인자 수정 - 김지영
  .github/workflows/solve-nyang-deploy.yml
Labels: bugfix

#19 [Fix] CD 적용 branch 설정
  .github/workflows/solve-nyang-deploy.yml
  src/main/java/com/ssafy/solvedpick/members/presentation/MemberController.java
  src/main/java/com/ssafy/solvedpick/members/service/MemberService.java
Labels: enhancement

#20 fix : security에 cors 설정 추가
  src/main/java/com/ssafy/solvedpick/config/SecurityConfig.java
Labels: bugfix

#21 fix: security config 수정
  src/main/java/com/ssafy/solvedpick/config/SecurityConfig.java
Labels: bugfix

#8 feat: 캐릭터 목록 전체 조회 API 구현 - 박찬영
  src/main/java/com/ssafy/solvedpick/avatars/domain/Avatar.java
  src/main/java/com/ssafy/solvedpick/avatars/dto/AvatarDto.java
  src/main/java/com/ssafy/solvedpick/avatars/dto/AvatarResponse.java
  src/main/java/com/ssafy/solvedpick/avatars/dto/GradeStatistics.java
  src/main/java/com/ssafy/solvedpick/avatars/presentation/AvatarController.java
  src/main/java/com/ssafy/solvedpick/avatars/service/AvatarService.java
  src/main/java/com/ssafy/solvedpick/config/SecurityConfig.java
Labels: feature

#22 refactor: package명 변경 및 유저 조회 로직 추가
  src/main/java/com/ssafy/solvedpick/accounts/service/SigninService.java
  src/main/java/com/ssafy/solvedpick/accounts/service/SignupService.java
  src/main/java/com/ssafy/solvedpick/accounts/service/VerificationService.java
  src/main/java/com/ssafy/solvedpick/auth/domain/VerificationKey.java
  src/main/java/com/ssafy/solvedpick/auth/dto/MemberNameDTO.java
  src/main/java/com/ssafy/solvedpick/auth/dto/SignInFormDTO.java
  src/main/java/com/ssafy/solvedpick/auth/dto/SignupFormDTO.java
  src/main/java/com/ssafy/solvedpick/auth/dto/TokenResponse.java
  src/main/java/com/ssafy/solvedpick/auth/dto/UsernameResponse.java
  src/main/java/com/ssafy/solvedpick/auth/dto/VerificationResponseDTO.java
  src/main/java/com/ssafy/solvedpick/auth/presentation/AuthController.java
  src/main/java/com/ssafy/solvedpick/auth/repository/VerificationKeyRepository.java
  src/main/java/com/ssafy/solvedpick/auth/scheduler/VerificationKeyScheduler.java
  src/main/java/com/ssafy/solvedpick/auth/service/AuthService.java
  src/main/java/com/ssafy/solvedpick/avatars/domain/Avatar.java
  src/main/java/com/ssafy/solvedpick/gacha/service/GachaService.java
  src/main/java/com/ssafy/solvedpick/members/presentation/MemberController.java
  src/main/java/com/ssafy/solvedpick/members/service/MemberService.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/impl/OwnedAvatarServiceImpl.java
Labels: enhancement

#23 fix: 필드 변경으로 인해 네이밍 수정
  src/main/java/com/ssafy/solvedpick/avatars/domain/Avatar.java
  src/main/java/com/ssafy/solvedpick/avatars/dto/AvatarDto.java
Labels: bugfix

#25 refactor: 회원이 필요한 컨트롤러, 서비스 수정 - 이동규
  src/main/java/com/ssafy/solvedpick/gacha/service/GachaService.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/presentation/OwnedAvatarController.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/OwnedAvatarService.java
  src/main/java/com/ssafy/solvedpick/ownedavatar/service/impl/OwnedAvatarServiceImpl.java
Labels: enhancement

#26 refactor: 정책 변경으로 인해 등급별 확률 수정 - 이동규
  src/main/java/com/ssafy/solvedpick/common/grade/Grade.java
Labels: enhancement
